# Assignment 8: Working with NumPy, Samia Mahmood, Version 1, Spring 2023

#### a. Create a 2-by-2 NumPy array with elements 10,20,30,40 in it. Then use broadcasting to perform each of these operations:

In [1]:
import numpy as np

In [14]:
a = np.array([[10,20], [30,40]])
a

array([[10, 20],
       [30, 40]])

i. Square every element of the array

In [15]:
b=a**2
print(b)

[[ 100  400]
 [ 900 1600]]


ii. Add 100 to every element of the array

In [16]:
c=a+100
print(c)

[[110 120]
 [130 140]]


iii. Multiply every element of the array by 5.

In [17]:
d=a*5
print(d)

[[ 50 100]
 [150 200]]


iv. Calculate the square root of each element in the array.

In [20]:
e=np.sqrt(a)
print(e)

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


#### b. Create a 3-by-3 array containing integers from 3 to 27 in multiples of 3.  Create a second 3-by-3 array with 9 elements evenly spaced between 10 and 20.  Multiply these arrays together and display the output

In [47]:
array1 = np.arange(3,28,3)

In [48]:
array1.resize(3,3)
array1

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [49]:
array2 = np.linspace(10,20,9)

In [51]:
array2.resize(3,3)
array2

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [52]:
array3 = array1*array2
array3

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

#### c.	Attached to the assignment are five .npy files that contain five values each. Read these files in and stack them into a unified dataset.  This would be a 5-by-5 NumPy array.  Then calculate the mean of each column of data

In [62]:
data1 = np.load('process1.npy')
data1

array([[52, 12, 81,  0, 58]])

In [63]:
data2 = np.load('process2.npy')
data2

array([[96,  4, 61, 16, 43]])

In [64]:
data3 = np.load('process3.npy')
data3

array([[38, 96, 45, 17, 58]])

In [66]:
data4 = np.load('process4.npy')
data4

array([[97, 21, 22, 25,  6]])

In [67]:
data5 = np.load('process5.npy')
data5

array([[77,  6, 19,  2, 74]])

In [72]:
dataset=np.concatenate([data1,data2,data3,data4,data5])

In [73]:
dataset

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]])

In [84]:
dataset.mean(axis=0)

array([72. , 27.8, 45.6, 12. , 47.8])